/**
 * Central app image resolver: Cloudinary URL when available, otherwise local path (fallback).
 * Map is generated by scripts/upload-images-to-cloudinary.cjs (uses server/.env Cloudinary keys).
 * Local images in public/images are kept as backup; use getAppImageUrl everywhere for static app images.
 */

import cloudinaryMapData from '@/lib/constants/cloudinary-image-map.json'

type CloudinaryMapPayload = {
  map: Record<string, string>
  generatedAt?: string
  cloudName?: string
  count?: number
}

const { map: cloudinaryMap } = (cloudinaryMapData as CloudinaryMapPayload) || { map: {} }

/**
 * Returns Cloudinary URL for the given path if it exists in the map, otherwise returns the local path.
 * This keeps local images as fallback until upload has been run and map is populated.
 * @param pathOrKey - Local path (e.g. "/images/drinkmate-logo.png") or key
 * @param options - Optional Cloudinary transform params (applied only for Cloudinary URLs)
 */
export function getAppImageUrl(
  pathOrKey: string,
  options?: { width?: number; quality?: number; fetchFormat?: 'auto' | 'webp' | 'avif' }
): string {
  const normalized = pathOrKey.startsWith('/') ? pathOrKey : `/${pathOrKey}`
  const cloudinaryUrl = cloudinaryMap[normalized]
  if (cloudinaryUrl) {
    if (options && (options.width != null || options.quality != null || options.fetchFormat)) {
      return buildCloudinaryUrl(cloudinaryUrl, options)
    }
    return cloudinaryUrl
  }
  return normalized
}

/**
 * Build Cloudinary URL with transformation segment (for optional width/quality/format).
 */
function buildCloudinaryUrl(
  baseUrl: string,
  opts: { width?: number; quality?: number; fetchFormat?: 'auto' | 'webp' | 'avif' }
): string {
  if (!baseUrl.includes('res.cloudinary.com') || !baseUrl.includes('/upload/')) return baseUrl
  const parts = baseUrl.split('/upload/')
  if (parts.length !== 2) return baseUrl
  const prefix = parts[0] + '/upload/'
  const path = parts[1]
  const transforms: string[] = ['q_auto', 'f_auto']
  if (opts.width != null) transforms.push(`w_${opts.width}`)
  if (opts.quality != null) transforms.push(`q_${opts.quality}`)
  if (opts.fetchFormat) transforms.push(`f_${opts.fetchFormat}`)
  return `${prefix}${transforms.join(',')}/${path}`
}

/**
 * Whether the given path has a Cloudinary URL in the map (useful for choosing loading="lazy" or priority).
 */
export function hasCloudinaryUrl(pathOrKey: string): boolean {
  const normalized = pathOrKey.startsWith('/') ? pathOrKey : `/${pathOrKey}`
  return Boolean(cloudinaryMap[normalized])
}
